version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
clone_depth: 10
build:
  project: nvmew/nvmew.sln
  verbosity: minimal
artifacts:
  - path: nvmew\Release\nvmew.exe
    name: x86 Release    

deploy:
  provider: GitHub
  auth_token:
    secure: MkEQ0qlYuJ9QhRNCsXoGXjTZrp/qMOiVDREvSP1DjQ+wEe6K9LM1w3SynDwDB1PW
  draft: false
  prerelease: false
  on:
    branch: master